# Generated by Django 5.2.7 on 2025-10-22 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='bookloan',
            options={'verbose_name': 'Выдача книги', 'verbose_name_plural': 'Выдачи книг'},
        ),
        migrations.AlterModelOptions(
            name='readerprofile',
            options={'verbose_name': 'Профиль читателя', 'verbose_name_plural': 'Профили читателей'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.AlterField(
            model_name='bookloan',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='bookloan',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок возврата'),
        ),
        migrations.AlterField(
            model_name='bookloan',
            name='loan_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='bookloan',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата возврата'),
        ),
        migrations.AlterField(
            model_name='bookloan',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('returned', 'Возвращена'), ('overdue', 'Просрочена')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='bookloan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='readerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='readerprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('librarian', 'Библиотекарь'), ('reader', 'Читатель')], default='reader', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='readerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата бронирования'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
