# Generated by Django 5.2.7 on 2025-10-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_alter_book_options_alter_bookloan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookloan',
            name='fine',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Штраф'),
        ),
        migrations.AddField(
            model_name='readerprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Баланс'),
        ),
    ]
