# Generated by Django 5.2.7 on 2025-10-22 04:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_bookloan_fine_readerprofile_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookloan',
            name='loan_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата выдачи'),
        ),
    ]
