# Generated by Django 5.2.7 on 2025-10-22 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_alter_reservation_options_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
    ]
