name: Django CI/CD Pipeline

# Запускаем при обновлениях в ветке main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # ==========================================
  # 1. ЭТАП CI: ТЕСТИРОВАНИЕ ПРОЕКТА
  # ==========================================
  test:
    name: Build and Test (CI)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: python manage.py migrate

      - name: Run tests
        run: python manage.py test

  # ==========================================
  # 2. ЭТАП CD: СБОРКА АРХИВА (АРТЕФАКТА)
  # ==========================================
  build-archive:
    name: Build Release Archive (CD)
    needs: test # Начинаем сборку ТОЛЬКО если тесты прошли успешно!
    runs-on: ubuntu-latest

    # Собираем архив только при пуше в main (не для pull request-ов)
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Создаем ZIP-архив проекта, исключая системные и мусорные файлы
      - name: Create ZIP archive
        run: |
          zip -r library_project_release.zip . -x "*.git*" "*.github*" "*.idea*" "*__pycache__*" "*.sqlite3" "venv/*"

      # Загружаем архив в GitHub Actions как готовый "Артефакт"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ready-project-archive # Имя файла, который можно будет скачать
          path: library_project_release.zip
          retention-days: 7 # Сколько дней архив будет храниться на GitHub
